language: python
python:
- '3.7'
install:
- pip3 install HookTest
script:  hooktest --console --scheme auto --guidelines 2.epidoc --workers 3 --verbose 7 --manifest --countword ./
before_deploy:
- hooktest-build --travis ./
- results=$(cat manifest.txt)
- DATE=`date +%Y-%m-%d`
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$major_version.$minor_version.$TRAVIS_BUILD_NUMBER
- git add -A
- git tag $GIT_TAG -a -m "$DATE" -m "PASSING FILES" -m "$results"
- git push -q https://$GITPERM@github.com/PatristicTextArchive/pta_data --tags
- ls -R

deploy:
  provider: releases
  api_key: $GITPERM
  skip_cleanup: true
  on:
    repo: PatristicTextArchive/pta_data
    branch: public

env:
  global:
    major_version: 1
    minor_version: 0
